### ISSUE TITLE
I got some problems when I install libs in Anaconda virtual environment.

### ISSUE THREAD

**Issue by chuck-park** [Team-Neighborhood/awesome-face-detection#2]
![image](https://user-images.githubusercontent.com/15935262/38509390-bd3aa878-3c5c-11e8-8ba3-7a63d5f36c80.png)
This is the error I got. I tried to figure it out. but it is hard to fix to me. 

![image](https://user-images.githubusercontent.com/15935262/38509474-edaa1b74-3c5c-11e8-9a4b-94765c2bf271.png)
And the same problem happened when I tried to install face_recognition too.

![image](https://user-images.githubusercontent.com/15935262/38509696-a4e9dcfc-3c5d-11e8-8d26-e2d6ef50a2e6.png)
And this error is about installing torch.

The only 'opencv-contrib-python' lib was installed successfully.

Can I know your system spec(OS, env, etc...)?

**Comment by tkwoo** [comment]
tested on osx, linux(debian, redhat). and used anaconda env.
I don't know how to install dlib on windows. probably,, build from src..?

**Comment by chuck-park** [comment]
Ok, I will try to figure it out some more. Thanks for your comment.

**Comment by xxllp** [comment]
@akadark , dlib 有whl 文件可以安装

**Comment by chuck-park** [comment]
@xxllp But I can't install dlib with anaconda prompt. How did you install that and where?

**Comment by junhwanjang** [comment]
@akadark On windows, you should check if your username in "English" or did you try this? https://anaconda.org/menpo/dlib

**Comment by chuck-park** [comment]
@junhwanjang Thanks!! It worked. And I am gonna try to install other packages!
